FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    paho-mqtt \
    influxdb-client

COPY scripts/plc_mqtt_subscriber.py /app/
COPY scripts/light_labels.py /app/

CMD ["python", "-u", "plc_mqtt_subscriber.py"]
