export const FACE_DETECT_INTERVAL = 500;
export const DETECTIONS_REQUIRED = 5;
export const GREETING_COOLDOWN = 30_000;
export const MAX_OVERLAY_DURATION = Infinity; // no time limit — session ends only via farewell or face-gone
export const JINGLE_DURATION = 30_000;
export const FACE_GONE_DISMISS_MS = 15_000;
export const MIN_GREETING_ALIVE_MS = 30_000;
export const CAROUSEL_MS = 30_000;
export const PAUSE_MS = 30_000;
export const PEAK_START = 6;
export const PEAK_END = 9;
export const QUOTE_COOLDOWN = 12 * 60 * 60 * 1000; // 12 hours (was 3 hours)
export const SILENCE_AUTO_SUMMARY_MS = 5_000;
export const BUS_CHECK_INTERVAL = 30_000;
export const BUS_LEAVE_SOON_MS = 15 * 60_000;
export const SILENCE_THRESHOLD = 0.015;
export const SILENCE_DURATION = 1500;
export const SILENCE_DURATION_SHORT = 700;
export const MIN_RECORDING_MS = 500;
export const MAX_RECORDING_MS = 10_000;
export const MAX_NATIVE_SILENCE = 5;
export const SWIPE_THRESHOLD = 50;
