"""MCP tools package for Building Automation server."""

from .generic import TOOLS as GENERIC_TOOLS, HANDLERS as GENERIC_HANDLERS
from .hvac import TOOLS as HVAC_TOOLS, HANDLERS as HVAC_HANDLERS
from .thermia import TOOLS as THERMIA_TOOLS, HANDLERS as THERMIA_HANDLERS
from .energy import TOOLS as ENERGY_TOOLS, HANDLERS as ENERGY_HANDLERS
from .sauna import TOOLS as SAUNA_TOOLS, HANDLERS as SAUNA_HANDLERS
from .external import TOOLS as EXTERNAL_TOOLS, HANDLERS as EXTERNAL_HANDLERS
from .daily_report import TOOLS as DAILY_REPORT_TOOLS, HANDLERS as DAILY_REPORT_HANDLERS
from .harmony import TOOLS as HARMONY_TOOLS, HANDLERS as HARMONY_HANDLERS
from .lights import TOOLS as LIGHTS_TOOLS, HANDLERS as LIGHTS_HANDLERS

ALL_TOOLS = (
    GENERIC_TOOLS + HVAC_TOOLS + THERMIA_TOOLS + ENERGY_TOOLS + SAUNA_TOOLS
    + EXTERNAL_TOOLS + DAILY_REPORT_TOOLS + HARMONY_TOOLS + LIGHTS_TOOLS
)

ALL_HANDLERS = {
    **GENERIC_HANDLERS,
    **HVAC_HANDLERS,
    **THERMIA_HANDLERS,
    **ENERGY_HANDLERS,
    **SAUNA_HANDLERS,
    **EXTERNAL_HANDLERS,
    **DAILY_REPORT_HANDLERS,
    **HARMONY_HANDLERS,
    **LIGHTS_HANDLERS,
}
